### ISSUE TITLE
Remembering hub IP

### ISSUE THREAD

**Issue by Mammad900** [Home-modules/webapp-android#1]
Currently the app will ask every time about the hub's IP address and port.

It has to remember the IP and launch the web app directly on subsequent starts.

**Comment by Mammad900** [comment]
- [x] Default IP is empty
- [x] Default port is 80
- [ ] Port changes to 443 on checking "is https" and vice versa
- [x] Trim whitespace
- [x] Don't allow "go"ing when IP or port is empty
- [x] Ping the hub and don't allow "go"ing when it is unreachable
- [x] Allow the user go to back to IP selection screen if hub becomes unreachable

**Comment by Mammad900** [comment]
> - [x] Port changes to 443 on checking "is https" and vice versa

Doesn't work

**Comment by Mammad900** [comment]
> Don't allow "go"ing when IP or port is empty

Works partially

**Comment by mohsenemx** [comment]
Remembring works fine, but app fails to display loaded data (from memory)

**Comment by mohsenemx** [comment]
This seems to be finally fixed. I'll close this once it's confirmed.

**Comment by Mammad900** [comment]
>  Port changes to 443 on checking "is https" and vice versa

Still doesn't work.
Also used to go directly to web app on subsequent starts but not anymore
