### ISSUE TITLE
Keyboard pushes the web app and tanks fps

### ISSUE THREAD

**Issue by Mammad900** [Home-modules/webapp-android#5]
Have it overlay instead.

**Comment by mohsenemx** [comment]
Fixed

**Comment by Mammad900** [comment]
The web app itself which is the actual problem is not fiexed

**Comment by Mammad900** [comment]
The change only applied to the IP screen which did not suffer from performance problems.

**Comment by Mammad900** [comment]
I think my phone is capable of doing this smoothly but it won't.

**Comment by mohsenemx** [comment]
I cannot fix keyboard pushing the screen on webapp, it's your job to fix as it's not related the application itself.

**Comment by Mammad900** [comment]
I can't do anything about this from the web app side. Keyboard is pushing the webview widget. You can do the same thing you did to the IP screen to the web app, as far as I know.

**Comment by mohsenemx** [comment]
Fixed before
