### ISSUE TITLE
IP selection screen style 

### ISSUE THREAD

**Issue by Mammad900** [Home-modules/webapp-android#6]
Style it like the login screen

**Comment by mohsenemx** [comment]
Fixed

**Comment by Mammad900** [comment]
![Screenshot_2023-06-22-10-53-55-191_com homemodules](https://github.com/Home-modules/webapp-android/assets/67197540/03fd31f2-fcfd-492f-a16b-1075bd1bda4d)

Umm no? This is quite different than the markup.

**Comment by mohsenemx** [comment]
Fixed. (Fr this time)

**Comment by Mammad900** [comment]
No

**Comment by Mammad900** [comment]
https://www.figma.com/file/HbSk05lVGoE5YRoaJsDChB/Untitled?type=design&node-id=0%3A1&mode=design&t=6LCvdDraDTkmjPmL-1
